function Hd = iir
%IIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
% Generated on: 23-Feb-2022 11:15:43

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 10000;  % Sampling Frequency

Fpass = 750;     % Passband Frequency
Fstop = 1250;    % Stopband Frequency
Apass = 1;       % Passband Ripple (dB)
Astop = 40;      % Stopband Attenuation (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match, 'FilterStructure', ...
            'df2sos');

[n,Wn] = ellipord(((pi/2)*Fpass)/Fs,((pi/2)*Fstop)/Fs,Apass,Astop);
[b,a] = ellip(n,Apass,Astop,((pi/2)*Fpass)/Fs)


% [EOF]
